/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function generateReceipt(bgPath: string, fontPath: string, outputPath: string, storeName: string, totalPrice: string): string

export declare function processImageRust(buffer: Uint8Array, width: number, height: number, grayscale: boolean): Buffer
