/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function compressImage(buffer: Uint8Array, width: number, height: number, grayscale: boolean): Buffer

export declare function generateReceipt(bgPath: string, fontPath: string, outputPath: string, storeName: string, storeAddress: string, items: Array<string>, totalPrice: string): string
